name: Run Playwright Tests in Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (optional but helpful)
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-playwright-tests .

      - name: Run tests inside Docker container
        run: docker run --rm my-playwright-tests

      - name: Copy HTML test report from container (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: /Users/user/ZEAL/playwright-report
